@extends('layouts.template')

@section('title', 'Pemesanan Tiket')

@section('content')
<section class="anime-details spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <div class="section-title">
                    <h4>Pemesanan Tiket</h4>
                </div>
                <div class="row">
                    {{-- Detail Film & Showtime --}}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100 bg-dark text-white">
                            <div class="card-body">
                                <h5 class="card-title">{{ $showtime->film->judul }}</h5>
                                <hr class="border-secondary">
                                <p class="card-text"><i class="fa fa-calendar"></i> Tanggal: {{ \Carbon\Carbon::parse($showtime->tanggal)->translatedFormat('d F Y') }}</p>
                                <p class="card-text"><i class="fa fa-clock-o"></i> Jam: {{ \Carbon\Carbon::parse($showtime->jam)->format('H:i') }}</p>
                                <p class="card-text"><i class="fa fa-usd"></i> Harga per Tiket: Rp {{ number_format($showtime->harga, 0, ',', '.') }}</p>
                                <p class="card-text"><i class="fa fa-chair"></i> Kursi Tersedia: <strong>{{ $availableCount }}</strong></p>
                                <p class="card-text"><i class="fa fa-film"></i> Ruangan: {{ $showtime->ruangan->nama }}</p>
                            </div>
                        </div>
                    </div>

                    {{-- Form Pemesanan --}}
                    <div class="col-lg-8 col-md-6 mb-4">
                        <div class="card h-100 bg-dark text-white">
                            <div class="card-body">
                                <h5 class="card-title">Formulir Pemesanan</h5>
                                <hr class="border-secondary">

                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif

                                <form action="{{ route('order.store') }}" method="POST" id="orderForm">
                                    @csrf
                                    <input type="hidden" name="showtime_id" value="{{ $showtime->id }}">
                                    <input type="hidden" id="harga_tiket" value="{{ $showtime->harga }}">

                                    <div class="form-group mb-4">
                                        <label for="jumlah_tiket" class="form-label">Jumlah Tiket</label>
                                        <input type="number" id="jumlah_tiket" name="jumlah_tiket" min="1" max="{{ $availableCount }}" value="{{ old('jumlah_tiket', 1) }}" class="form-control" required>
                                    </div>

                                    <div class="form-group mb-4" id="seat-selection-container">
                                        <label class="form-label">Pilih Kursi</label>
                                        <div id="seat-select-div">
                                            {{-- Seat select fields will be generated by JS here --}}
                                        </div>
                                    </div>

                                    <div class="mb-4">
                                        <h5 class="total-price-text">
                                            Total Harga: <span id="total_harga_display">Rp. 0</span>
                                        </h5>
                                    </div>

                                    <button type="submit" class="site-btn">Pesan Sekarang</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{{-- Pastikan semua script JS tetap ada di sini --}}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const qty = document.getElementById('jumlah_tiket');
        const seatDiv = document.getElementById('seat-select-div');
        const totalHargaDisplay = document.getElementById('total_harga_display');
        const hargaPerTiket = document.getElementById('harga_tiket').value;

        // Ambil data kursi dari PHP ke JavaScript
        // Perbaikan: Ganti $seats dengan $availableSeats
        const seats = {!! json_encode($availableSeats->pluck('nomor_kursi', 'id')) !!};

        function updateTotal() {
            const numTickets = parseInt(qty.value) || 0;
            const total = numTickets * hargaPerTiket;
            totalHargaDisplay.textContent = `Rp ${new Intl.NumberFormat('id-ID').format(total)}`;
            generateSeatFields(numTickets);
        }

        function generateSeatFields(count) {
            seatDiv.innerHTML = '';
            for (let i = 1; i <= count; i++) {
                const wrapper = document.createElement('div');
                wrapper.classList.add('seat-select-wrapper', 'mb-2');

                const select = document.createElement('select');
                select.name = `kursi[]`;
                select.classList.add('form-control', 'nice-select');
                select.required = true;

                const optDefault = document.createElement('option');
                optDefault.value = '';
                optDefault.textContent = `-- Pilih Kursi ${i} --`;
                select.appendChild(optDefault);

                for (const [id, nomor] of Object.entries(seats)) {
                    const opt = document.createElement('option');
                    opt.value = id;
                    opt.textContent = `Kursi ${nomor}`;
                    select.appendChild(opt);
                }

                wrapper.appendChild(select);
                seatDiv.appendChild(wrapper);
            }

            seatDiv.querySelectorAll('select').forEach(sel => {
                sel.addEventListener('change', preventDuplicate);
            });
        }

        function preventDuplicate() {
            const selected = Array.from(seatDiv.querySelectorAll('select'))
                .map(sel => sel.value)
                .filter(v => v !== '');

            seatDiv.querySelectorAll('select').forEach(sel => {
                Array.from(sel.options).forEach(opt => {
                    if (opt.value !== '' && selected.includes(opt.value) && sel.value !== opt.value) {
                        opt.disabled = true;
                    } else {
                        opt.disabled = false;
                    }
                });
            });
        }

        qty.addEventListener('input', updateTotal);
        updateTotal(); // jalankan saat awal
    });
</script>
@endsection